from hello_world.hello_world import hello_world
from hello_world_uart.hello_world_uart import hello_world_uart
from user_proj_tests.ram4k_smoke_test.ram4k_smoke_test import ram4k_smoke_test
from user_proj_tests.ram4k_word_test.ram4k_word_test import ram4k_word_test
from gpio_test.gpio_test import gpio_test